### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by wybran** [ElektronPlus/sanavaulth#6]

**Comment by wybran** [comment]
![Image](https://user-images.githubusercontent.com/19632192/201516238-0bdb5502-003d-4c47-ba1f-f9175e39f15f.png)

**Comment by wybran** [comment]
LGTM

**Comment by Mopsior** [comment]
make dark design too

**Comment by mtatko** [comment]
![sanavaulth_black](https://user-images.githubusercontent.com/60148744/202144019-2cd0573e-23cf-406d-a7bb-c1992986c1e3.svg)
![sanavaulth_white](https://user-images.githubusercontent.com/60148744/202143795-2fcb0755-f231-4ab2-91e7-043d6202f76f.svg)
